parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Api\Action\:
    resource: '../src/Api/Action'
    tags: ['controller.service_arguments']

  App\Api\Listener\JsonExceptionResponseTransformerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

  App\Api\Listener\JWTCreatedListener :
    tags :
      - { name : kernel.event_listener, event : lexik_jwt_authentication.on_jwt_created, method : onJWTCreated }